# Generated by Django 5.2.5 on 2025-09-14 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedGameData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("co2_tons", models.FloatField(default=0)),
                ("citizen_satisfaction", models.CharField(blank=True, max_length=100)),
                ("budget", models.IntegerField(default=0)),
                ("top_tags", models.TextField(blank=True)),
                ("ai_city_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_game",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "저장된 게임 데이터",
                "verbose_name_plural": "저장된 게임 데이터들",
                "db_table": "saved_game_data",
            },
        ),
    ]
